### ISSUE TITLE
Doesn't copy text inside an element that has a class

### ISSUE THREAD

**Issue by justsomebodyhere** [superevilmegaco/copy-element-text#1]
Example: it doesn't copy text in `<h2 class="foo">Heading</h2>`

**Comment by justsomebodyhere** [comment]
Same is the case if an outer element has a class. Example: it doesn't copy text in the following:

`<div class="mkd-column-inner"><h1>Heading</h1></div>`

**Comment by gorillamoe** [comment]
I can't reproduce this issue. Do you have a link to a webpage, where this occurs to you?
