### ISSUE TITLE
[Bug] Cannot copy any element's text : "Cannot read properties of undefined (reading 'writeText')"

### ISSUE THREAD

**Issue by KaKi87** [superevilmegaco/copy-element-text#2]
Hello,

The following error is thrown anytime I try to copy any element's text on the following page : http://www.synonymo.fr/synonyme/imagination

```
imagination:1 Error in event handler: TypeError: Cannot read properties of undefined (reading 'writeText')
    at toClipboard (chrome-extension://lejdjhmnhlhjhfmcalaimioiogkibdea/boot.js:5:23)
    at chrome-extension://lejdjhmnhlhjhfmcalaimioiogkibdea/boot.js:19:7
```

Thanks

**Comment by gorillamoe** [comment]
Hey hey, sorry for the late response, but was pretty busy. I can't reproduce this issue with the current release. Do you still have this error?

**Comment by KaKi87** [comment]
Hmm, I can't seem to reproduce it, no, despite there was no release since then 🤔
