### ISSUE TITLE
Copy using WebExtensions API instead of window clipboard API

### ISSUE THREAD

**Issue by KaKi87** [superevilmegaco/copy-element-text#3]
Hi,

It would be nice to use the WebExtensions API to copy content to clipboard instead of the window clipboard API, so that the extension wouldn't have to request permission for every site it's used on.

Thanks

**Comment by gorillamoe** [comment]
Hey @KaKi87, thanks for the suggestion, but AFAIK it's not (yet) supported: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#webextensions.api.clipboard

**Comment by KaKi87** [comment]
Oh, I wonder how are userscript managers achieving this with `GM.setClipboard` then :thinking:

**Comment by gorillamoe** [comment]
I'll look into this, later, when I'm back. I'll go and checkout the violentmonkey source I guess :)

**Comment by gorillamoe** [comment]
ViolentMonkey seems to use a similar copy mechanism as this extension.

https://github.com/violentmonkey/violentmonkey/blob/24e7fa83822e1628b2b40707ac755f6ad3fa22b8/src/background/utils/clipboard.js#L10

I'll change this extension's bevaviour to match the one of ViolentMonkey. This might probably fix your issue.

**Comment by gorillamoe** [comment]
Have to dig a bit deeper. ViolentMonkey uses `document.execCommand` which is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by gorillamoe** [comment]
There is an update in the Chrome Web store. Can you check if the update fixes your issue? It should be v1.0.1.

Don't forget to reload tabs after the installation, or else the extension might not work.
